---
- name: Check if phpunit is installed.
  stat: 
    path: /usr/local/bin/phpunit
  register: phpunit_bin

- name: Install PHPUnit
  get_url:
    url: https://phar.phpunit.de/phpunit-6.1.phar
    dest: /usr/local/bin/phpunit
    owner: root
    group: root
    mode: 0755
  when: not phpunit_bin.stat.exists
